version: 2

aliases:
  - &defaults
    docker:
      - image: circleci/node:10


jobs:
  dependencies:
    <<: *defaults
    steps:
      - run:
          name: Checkout maple-beta-scaffold
          command: GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:maple-labs/maple-beta-scaffold.git .
      - run:
          name: Checkout mbs dependencies
          command: GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" yarn setup
      - restore_cache:
          key: v1-npm-deps-{{ checksum "~/project/package-lock.json" }}
      - run:
          name: Checkout current maple-core branch
          command: cd ~/project/packages/maple-core && git checkout $CIRCLE_BRANCH
      - run:
          name: Install maple-core deps
          command: npm i # Have to use NPM here beacuse we're checksumming the package-lock
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
              - "./*"

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/project
      - run:
          name: Install hardhat globally
          command: npm i -g hardhat
      - run:
          name: Run mbs chain
          command: cd ~/project && yarn chain >> /dev/null # Note: pipe this to /dev/null once happy with config
          background: true
      - run:
          name: Wait for chain to start
          command: sleep 3
      - run:
          name: Run tests for maple-core
          command: cd ~/project && yarn all:test

  teardown:
    <<: *defaults
    steps:
      - run:
          name: Stop mbs chain
          command: pkill node

workflows:
  version: 2
  test_all:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
      - teardown:
          requires:
            - test
