version: 2

aliases:
  - &defaults
    docker:
      - image: circleci/node:10

jobs:
  dependencies:
    <<: *defaults
    steps:
      - run:
          name: Checkout maple-beta-scaffold
          command: GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:maple-labs/maple-beta-scaffold.git .
      - run:
          name: Checkout mbs dependencies
          command: yarn setup
      - run:
          name: Checkout current maple-core branch
          command: cd ~/project/packages/maple-core && git checkout $CIRCLE_BRANCH
      - run:
          name: Install maple-core deps
          command: yarn

  test:
    <<: *defaults
    steps:
      - run:
          name: Run mbs chain
          command: cd ~/project && yarn chain >> /dev/null & # Note: pipe this to /dev/null once happy with config
      - run:
          name: Run tests for maple-core
          command: cd ~/project && yarn all:test

  teardown:
    <<: *defaults
    steps:
      - run:
          name: Stop mbs chain
          command: pkill node

workflows:
  version: 2
  everything:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
      - teardown:
          requires:
            - dependencies
            - test
